'use client';

import { useRef, useState } from 'react';
import { motion } from 'framer-motion';
import { ImageAnalysisResponse } from '@/types/image-analysis';
import { toast } from 'sonner';
import imageAnalysisService from '@/lib/tools/image-analysis.service';
import { ImageAnalysisInput } from './components/image-analysis-input';
import { ImageAnalysisResults } from './components/image-analysis-results';

export default function ImageAnalysis() {
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [imageData, setImageData] = useState<ImageAnalysisResponse | null>(null);
    const [imagePreview, setImagePreview] = useState<string | null>(null);

    const inputFormRef = useRef<{ reset: () => void } | null>(null);

    /* 🌱 Función para manejar el análisis de la imagen */
    const handleAnalyze = async (data: {
        imageSource: File | string;
        saveToDb: boolean;
        storeFile: boolean;
    }) => {
        setImageData(null);
        setError(null);
        setLoading(true);

        try {
            let response: ImageAnalysisResponse;

            if (typeof data.imageSource === 'string') {
                setImagePreview(data.imageSource);
                response = await imageAnalysisService.analyzeImageFromUrl(
                    data.imageSource,
                    data.saveToDb,
                    data.storeFile
                );
            } else {
                const objectUrl = URL.createObjectURL(data.imageSource);
                setImagePreview(objectUrl);
                response = await imageAnalysisService.analyzeImageFromFile(
                    data.imageSource,
                    data.saveToDb,
                    data.storeFile
                );
            }

            if (!response.success || !response.data) {
                setError(response.message || 'Error analyzing the image.');
                setImageData(null);

                toast.error('Analysis error', {
                    description: response.message || 'Could not process the image.'
                });
            } else {
                setImageData(response);

                const verdict = response.data.report.verdict === 'ai' ? 'AI' : 'Human';
                const confidence = Math.round(
                    response.data.report.verdict === 'ai'
                        ? response.data.report.ai.confidence * 100
                        : response.data.report.human.confidence * 100
                );

                toast.success('Analysis completed', {
                    description: `Result: ${verdict} (${confidence}% confidence)`
                });
            }
        } catch (err) {
            const errorMessage = 'Error processing the request. Please try again.';
            setError(errorMessage);
            setImageData(null);

            toast.error('Error', {
                description: errorMessage
            });
        } finally {
            setLoading(false);
        }
    };

    /* Función para restablecer el formulario */
    const handleReset = () => {
        setImageData(null);
        setError(null);
        setLoading(false);
        setImagePreview(null);

        if (inputFormRef.current && typeof inputFormRef.current.reset === 'function') {
            inputFormRef.current.reset();
        }

        toast.info('Form reset', {
            description: 'All data has been cleared for a new analysis.'
        });
    };

    return (
        <>
            <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: 0.1 }}
                className='mb-6 flex items-center justify-between'
            >
                <div>
                    <h1 className='text-2xl font-bold tracking-tight'>Image Analysis</h1>
                    <p className='text-muted-foreground text-sm'>
                        Determine if an image was created by humans or generated by artificial
                        intelligence.
                    </p>
                </div>
            </motion.div>

            <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: 0.2 }}
                className='grid gap-6 lg:grid-cols-2'
            >
                {/* Analysis input form */}
                <ImageAnalysisInput
                    ref={inputFormRef}
                    onSubmit={handleAnalyze}
                    onReset={handleReset}
                    isLoading={loading}
                />

                {/* Results visualization */}
                <ImageAnalysisResults
                    data={imageData}
                    error={error}
                    isLoading={loading}
                    imagePreview={imagePreview}
                />
            </motion.div>
        </>
    );
}
