import {
    IconAlertTriangle,
    IconArrowRight,
    IconCheck,
    IconChevronLeft,
    IconChevronRight,
    IconCommand,
    IconCreditCard,
    IconFile,
    IconFileText,
    IconHelpCircle,
    IconPhoto,
    IconDeviceLaptop,
    IconLayoutDashboard,
    IconLoader2,
    IconLogin,
    IconProps,
    IconShoppingBag,
    IconMoon,
    IconDotsVertical,
    IconPizza,
    IconPlus,
    IconSettings,
    IconSun,
    IconTrash,
    IconBrandTwitter,
    IconUser,
    IconUserCircle,
    IconUserEdit,
    IconUserX,
    IconX,
    IconLayoutKanban,
    IconBrandGithub,
    IconEdit,
    IconRefresh,
    IconDeviceFloppy,
    IconRotateClockwise,
    IconRoute,
    IconServer,
    IconLink,
    IconCloudDownload,
    IconCloudUpload
} from '@tabler/icons-react';
import { link } from 'fs';
import { Settings } from 'lucide-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
    dashboard: IconLayoutDashboard,
    logo: IconCommand,
    login: IconLogin,
    close: IconX,
    product: IconShoppingBag,
    spinner: IconLoader2,
    kanban: IconLayoutKanban,
    chevronLeft: IconChevronLeft,
    chevronRight: IconChevronRight,
    trash: IconTrash,
    employee: IconUserX,
    post: IconFileText,
    page: IconFile,
    userPen: IconUserEdit,
    user2: IconUserCircle,
    media: IconPhoto,
    settings: IconSettings,
    billing: IconCreditCard,
    ellipsis: IconDotsVertical,
    add: IconPlus,
    warning: IconAlertTriangle,
    user: IconUser,
    arrowRight: IconArrowRight,
    help: IconHelpCircle,
    pizza: IconPizza,
    sun: IconSun,
    moon: IconMoon,
    laptop: IconDeviceLaptop,
    github: IconBrandGithub,
    twitter: IconBrandTwitter,
    check: IconCheck,
    server: IconServer,
    route: IconRoute,
    edit: IconEdit,
    refresh: IconRefresh,
    save: IconDeviceFloppy,
    rotateCw: IconRotateClockwise,
    x: IconX,
    plus: IconPlus,
    tools: Settings,
    link: IconLink,
    cloudDownload: IconCloudDownload,
    cloudUpload: IconCloudUpload
};
